In [74]:
import numpy as np

In [75]:
class Dense:
    """A fully-connected NN layer.
    Parameters:
    -----------
    n_output: int
        The number of neurons in the layer.
    n_input: int
        The expected input shape of the layer. For dense layers a single digit specifying
        the number of features of the input. Must be specified if it is the first layer in
        the network.
    """

    def __init__(self, n_output, n_input=None):
        self.layer_input = None
        self.n_input = n_input
        self.n_output = n_output
        self.trainable = True
        self.W = None
        self.bias = None
        self.initialize()

    def initialize(self):
        # Initialize the weights
        np.random.seed(42)
        self.W = np.random.normal(0.0, 1, (self.n_input, self.n_output))
        self.bias = np.random.random(size=(self.n_output))

    '''def forward_pass_a(self, X):
        output = np.zeros(3)
        for row in range()
        for i in range(self.n_output):
            temp = 0
            for j in range(self.n_output):
                temp += X[j]*self.W[j, i]
            output[i] = temp + self.bias[i]

        return output'''

    def forward_pass_a(self, X):
        return X @ self.W + self.bias

In [76]:
input_data = np.array([[1, 2, 3, 4, 5]])
input_data.resize((5,))
print(input_data)
#input_data = np.array([1, 2, 3, 4, 5])
print(input_data)
layer = Dense(3, n_input=5)

output = layer.forward_pass_a(input_data)
print(output)

[1 2 3 4 5]
[1 2 3 4 5]
[ 12.27231674  -9.584845   -11.42437206]


In [77]:
class ReLU():
    def forward_pass(self, x):
        return np.where(x >= 0, x, 0)

In [78]:
activation = ReLU()
print(activation.forward_pass(output))

[12.27231674  0.          0.        ]


In [79]:
import GYAK10
from importlib import reload
GYAK10 = reload(GYAK10)
from GYAK10 import Dense, ReLU



In [82]:
input_data = np.array([[1, 2, 3, 4, 5]])
input_data.resize((5,))
print(input_data)
#input_data = np.array([1, 2, 3, 4, 5])
print(input_data)
layer = GYAK10.Dense(3, n_input=5)

output = layer.forward_pass_a(input_data)
print(output)

[1 2 3 4 5]
[1 2 3 4 5]
[ 12.27231674  -9.584845   -11.42437206]


In [81]:
activation = ReLU()
print(activation.forward_pass(output))

[12.27231674  0.          0.        ]
